// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace BookLibrary.Models.PageModels;

[Keyless]
[Table("userShelfs")]
[Index("ProfileId", Name = "profile_un")]
[Index("ShelfId", Name = "shelf_id")]
public partial class UserShelfs
{
    [Column("shelf_id", TypeName = "int(11)")]
    public int ShelfId { get; set; }

    [Column("profile_un")]

    public string ProfileUn { get; set; }

    [ForeignKey("ProfileId")]
    public virtual ApplicationUser Profile { get; set; }

    [ForeignKey("ShelfId")]
    public virtual Shelfs Shelf { get; set; }
}